In [1]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

C:\Users\Vansh\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
dataset_path = "C:\Code\Infrared\Model"

In [3]:
def load_dataset():
    images = []
    labels = []
    
    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            image_path = os.path.join(root, file)
            label = os.path.basename(root)
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            image = cv2.resize(image, (64, 64)) 
            image = image.flatten()
            images.append(image)
            labels.append(label)
    images = np.array(images)
    labels = np.array(labels)
    return images, labels

In [4]:
images, labels = load_dataset()

In [5]:
print(images)
print(labels)

[[255 255 255 ... 255 255 255]
 [ 48  48  49 ... 142 144 144]
 [ 36  36  36 ...  10  10  10]
 ...
 [255 255 255 ... 255 255 255]
 [  0   0   0 ...   0   0   0]
 [255 255 255 ... 255 255 255]]
['Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset'
 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset'
 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Dataset'
 'Dataset' 'Dataset' 'Dataset' 'Dataset' 'Testing Images' 'Testing Images'
 'Testing Images' 'Testing Images' 'Testing Images' 'Testing Images'
 'Testing Images' 'Testing Images' 'Testing Images' 'Testing Images'
 'Testing Images' 'Testing Images' 'Testing Images' 'Testing Images'
 'Testing Images' 'Testing Images' 'Testing Images' 'Testing Images'
 'Testing Images' 'Testing Images']


In [6]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.15, random_state=50)                     

In [7]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [8]:
y_pred = gnb.predict(X_test)

In [9]:
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):",metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 85.71428571428571
